# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "tzahitamirtf"
    dynamodb_table = "terraform-state-locking"
    encrypt        = true
    key            = "tf/myterragrunt/dev/stacks/sg/terraform.tfstate"
    region         = "us-east-1"
  }
}
