name: "Terraform (my)"

on:
  push:
    paths:
      - "private26/my/**"

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        stack:
          - private26/my/dev/stacks/s3
          - private26/my/network/stacks/s3
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::890387921239:role/gh-actions-tf
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.8"
          terraform_wrapper: false

      - name: Terraform Format Check
        working-directory: ${{ matrix.stack }}
        run: terraform fmt -check -diff

      - name: Terraform Init
        working-directory: ${{ matrix.stack }}
        run: terraform init -input=false

      - name: Terraform Plan
        working-directory: ${{ matrix.stack }}
        run: terraform plan -no-color -input=false

  apply:
    needs: plan
    runs-on: ubuntu-latest
    environment: production
    strategy:
      fail-fast: false
      matrix:
        stack:
          - private26/my/dev/stacks/s3
          - private26/my/network/stacks/s3
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::890387921239:role/gh-actions-tf
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.8"
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: ${{ matrix.stack }}
        run: terraform init -input=false

      - name: Terraform Apply
        working-directory: ${{ matrix.stack }}
        run: terraform apply -auto-approve -input=false
